name: Continuous Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    name: Publish to pkg.pr.new
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[cr publish]')
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm i
      - run: pnpm build

      - run: pnpx pkg-pr-new publish --pnpm
