name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches-ignore: [latest]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm i
      - run: pnpm lint --fix
        continue-on-error: true

      - uses: autofix-ci/action@v1.3.1
        with:
          commit-message: 'style: autofix'
