name: Publish Release

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  sync-latest-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git checkout -b latest origin/latest
          git merge --ff-only origin/main
          git push origin latest

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm i
      - run: pnpm build

      - run: npm config set '//registry.npmjs.com/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - run: pnpm publish --provenance --access=public --no-git-checks
