name: Publish Release

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  sync-latest-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - run: |
          git checkout -b latest origin/latest
          git merge --ff-only origin/main
          git push origin latest

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version-file: .tool-versions

      - run: bun i
      - run: bun run build
      - run: npm config set //registry.npmjs.org/:_authToken "${{ secrets.NPM_ACCESS_TOKEN }}"
      - run: bunx npm publish
